#!/usr/bin/env python3
"""
profile_generator.py
====================

The offline / admin tool that builds and updates a **measured palette profile**
(see Color-engine.docx).  This is the default production path the doc review
mandated (rule R5): profiles are generated by the backend/admin ahead of time and
then loaded from cache by the app -- TryColors is never called on a user action.

What it does, given a palette (color names + hex):

1. Load the existing profile for this ``palette_id`` (if any) and merge in the
   requested colors, preserving existing color ids.  Adding a color therefore
   only adds the new pair comparisons (rule R4 -- incremental).
2. Diff the expected pairwise comparisons against what the profile already has.
3. For each missing comparison, measure the mix.  Hybrid strategy (chosen by the
   user): use the real TryColors ``pro``/``2025`` endpoint as ground truth, and
   fall back to the local Kubelka-Munk engine when the daily API budget is
   exhausted -- so a big palette keeps making progress and can resume tomorrow.
4. Save the profile (versioned) and report completeness + remaining budget.

Usage::

    python profile_generator.py --palette-id studio-set-a --name "Studio Set A" \
        --colors '[{"name":"Cad Yellow","hex":"#FEE100"},{"name":"Ultramarine","hex":"#19123F"}]'

    python profile_generator.py --palette-id studio-set-a --colors-file colors.json
    python profile_generator.py --palette-id studio-set-a ... --local-only   # no API calls
    python profile_generator.py --palette-id studio-set-a ... --max 20        # cap this run

Nothing here is exposed to end users; the API key is read server-side by
``trycolors_client`` (rule R8).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import measured_profile as mp
from trycolors_client import BudgetExhausted, MissingApiKey, TryColorsClient, TryColorsError

# Local Kubelka-Munk fallback engine (same physical model the app's KM unmix uses).
from custom_palette_unmix import _mix_hex as _km_mix_hex


def _parse_ratios(s: Optional[str]) -> List[Tuple[int, int]]:
    if not s:
        return mp.DEFAULT_RATIOS
    out: List[Tuple[int, int]] = []
    for tok in s.split(","):
        a, b = tok.strip().split(":")
        out.append((int(a), int(b)))
    return out


def _local_mix(profile: Dict, comp: Dict) -> str:
    """Local KM forward mix for a comparison (fallback when API budget is spent)."""
    id_to_hex = {c["id"]: c["hex"] for c in profile["colors"]}
    hexes = [id_to_hex[p] for p in comp["pigments"]]
    weights = [float(x) for x in comp["parts"]]
    return _km_mix_hex(hexes, weights, method="kubelka_munk")


def generate(
    palette_id: str,
    colors: Sequence[Dict[str, str]],
    *,
    palette_name: str = "",
    ratios: Optional[Sequence[Tuple[int, int]]] = None,
    use_api: bool = True,
    local_only: bool = False,
    max_this_run: Optional[int] = None,
    profiles_dir: Optional[Path] = None,
    client: Optional[TryColorsClient] = None,
) -> Dict:
    """Build/update the profile for ``palette_id``.  Returns the saved profile."""
    ratios = list(ratios) if ratios is not None else mp.DEFAULT_RATIOS

    profile = mp.load_profile(palette_id, profiles_dir)
    if profile is None:
        profile = mp.new_profile(colors, palette_id=palette_id, palette_name=palette_name)
    else:
        if palette_name:
            profile["palette_name"] = palette_name
        mp.update_profile_colors(profile, colors)

    missing = mp.diff_missing(profile, ratios=ratios)
    if max_this_run is not None:
        missing = missing[: max(0, int(max_this_run))]

    if not missing:
        mp.recompute_completeness(profile, ratios)
        mp.save_profile(profile, profiles_dir)
        print(f"[generate] {palette_id}: already complete "
              f"({profile['completeness']['present_count']}/{profile['completeness']['expected_count']}).")
        return profile

    if client is None and use_api and not local_only:
        try:
            client = TryColorsClient()
        except Exception as exc:  # pragma: no cover - defensive
            print(f"[generate] could not init TryColors client ({exc}); using local engine.")
            client = None

    results: List[Dict] = []
    n_api = 0
    n_local = 0
    budget_done = local_only or not use_api or client is None

    for comp in missing:
        used_api = False
        mixed_hex: Optional[str] = None
        if not budget_done:
            colors_payload = _comparison_payload(profile, comp)
            try:
                res = client.mix(colors_payload)
                mixed_hex = res.mixed_hex
                used_api = True
            except BudgetExhausted as exc:
                print(f"[generate] {exc} Switching to local engine for the rest of this run.")
                budget_done = True
            except (MissingApiKey, TryColorsError) as exc:
                print(f"[generate] API error ({exc}); using local engine for this comparison.")

        if mixed_hex is None:
            mixed_hex = _local_mix(profile, comp)
            n_local += 1
            source = "local_km"
        else:
            n_api += 1
            source = "trycolors_api"

        results.append({
            "pigments": comp["pigments"],
            "parts": comp["parts"],
            "trycolors_result_hex": mixed_hex,
            "source": source,
        })
        if used_api:
            print(f"[api ] {comp['pigments']} {comp['parts']} -> {mixed_hex}")
        else:
            print(f"[local] {comp['pigments']} {comp['parts']} -> {mixed_hex}")

    mp.add_results(profile, results)
    mp.recompute_completeness(profile, ratios)
    mp.bump_version(profile)
    saved = mp.save_profile(profile, profiles_dir)

    comp_state = profile["completeness"]
    remaining = client.remaining_budget() if client is not None else 0
    print(f"[generate] {palette_id}: +{len(results)} comparisons "
          f"({n_api} via API, {n_local} via local engine). "
          f"Completeness {comp_state['present_count']}/{comp_state['expected_count']} "
          f"(complete={comp_state['complete']}). Profile v{profile['profile_version']}. "
          f"API budget remaining today: {remaining}. Saved -> {saved}")
    if comp_state["missing"]:
        print(f"[generate] {len(comp_state['missing'])} comparisons still missing "
              f"-- re-run to continue (resumable).")
    return profile


def _comparison_payload(profile: Dict, comp: Dict) -> List[Dict[str, object]]:
    id_to_hex = {c["id"]: c["hex"] for c in profile["colors"]}
    return [{"hex": id_to_hex[p], "count": int(part)}
            for p, part in zip(comp["pigments"], comp["parts"])]


def _load_colors(args) -> List[Dict[str, str]]:
    if args.colors_file:
        data = json.loads(Path(args.colors_file).read_text())
    elif args.colors:
        data = json.loads(args.colors)
    else:
        raise SystemExit("Provide --colors '<json>' or --colors-file <path>.")
    if not isinstance(data, list):
        raise SystemExit("colors must be a JSON list of {name,hex}.")
    return data


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Generate/update a measured palette profile (admin tool).")
    ap.add_argument("--palette-id", default=None,
                    help="Stable palette id (reuse it to add colors incrementally). "
                         "If omitted, derived from the exact color set, which is what "
                         "/unmix/custom auto-looks-up when the frontend sends no palette_id.")
    ap.add_argument("--name", default="", help="Human-readable palette name.")
    ap.add_argument("--colors", help="JSON list of {name,hex}.")
    ap.add_argument("--colors-file", help="Path to a JSON file with a list of {name,hex}.")
    ap.add_argument("--ratios", help="Comma-separated pairwise ratios, e.g. '1:1,1:3,3:1'.")
    ap.add_argument("--max", type=int, default=None, help="Cap comparisons generated this run.")
    ap.add_argument("--local-only", action="store_true", help="Never call the API; use the local KM engine only.")
    ap.add_argument("--no-api", action="store_true", help="Alias for --local-only.")
    ap.add_argument("--profiles-dir", default=None, help="Override the profiles directory.")
    args = ap.parse_args(argv)

    colors = _load_colors(args)
    profiles_dir = Path(args.profiles_dir) if args.profiles_dir else None
    palette_id = args.palette_id or mp.palette_id_for(colors)
    if not args.palette_id:
        print(f"[generate] no --palette-id given; using derived id '{palette_id}' "
              f"(this is what /unmix/custom auto-matches for these exact colors).")
    generate(
        palette_id=palette_id,
        colors=colors,
        palette_name=args.name,
        ratios=_parse_ratios(args.ratios),
        use_api=not (args.local_only or args.no_api),
        local_only=args.local_only or args.no_api,
        max_this_run=args.max,
        profiles_dir=profiles_dir,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
